make[1]: Entering directory '/home/mohamed/research/thread_lib/gnu-pth'
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/bin
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/include
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/lib
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/man/man1
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/man/man3
./shtool mkdir -f -p -m 755 /home/mohamed/research/thread_lib/gnu-pth/install/share/aclocal
./shtool install -c -m 755 pth-config /home/mohamed/research/thread_lib/gnu-pth/install/bin/pth-config
./shtool install -c -m 644 pth-config.1 /home/mohamed/research/thread_lib/gnu-pth/install/man/man1/pth-config.1
./shtool install -c -m 644 pth.3 /home/mohamed/research/thread_lib/gnu-pth/install/man/man3/pth.3
./shtool install -c -m 644 pth.m4 /home/mohamed/research/thread_lib/gnu-pth/install/share/aclocal/pth.m4
./shtool install -c -m 644 pth.h /home/mohamed/research/thread_lib/gnu-pth/install/include/pth.h
./shtool install -c .libs/libpth.so.20.0.27 /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpth.so.20.0.27
(cd /home/mohamed/research/thread_lib/gnu-pth/install/lib && { ln -s -f libpth.so.20.0.27 libpth.so.20 || { rm -f libpth.so.20 && ln -s libpth.so.20.0.27 libpth.so.20; }; })
(cd /home/mohamed/research/thread_lib/gnu-pth/install/lib && { ln -s -f libpth.so.20.0.27 libpth.so || { rm -f libpth.so && ln -s libpth.so.20.0.27 libpth.so; }; })
./shtool install -c .libs/libpth.lai /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpth.la
./shtool install -c .libs/libpth.a /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpth.a
chmod 644 /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpth.a
ranlib /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpth.a
PATH="$PATH:/sbin" ldconfig -n /home/mohamed/research/thread_lib/gnu-pth/install/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/mohamed/research/thread_lib/gnu-pth/install/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
./shtool install -c -m 755 pthread-config /home/mohamed/research/thread_lib/gnu-pth/install/bin/pthread-config
./shtool install -c -m 644 pthread-config.1 /home/mohamed/research/thread_lib/gnu-pth/install/man/man1/pthread-config.1
./shtool install -c -m 644 pthread.h /home/mohamed/research/thread_lib/gnu-pth/install/include/pthread.h
./shtool install -c -m 644 pthread.3 /home/mohamed/research/thread_lib/gnu-pth/install/man/man3/pthread.3
./shtool install -c .libs/libpthread.so.20.0.27 /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpthread.so.20.0.27
(cd /home/mohamed/research/thread_lib/gnu-pth/install/lib && { ln -s -f libpthread.so.20.0.27 libpthread.so.20 || { rm -f libpthread.so.20 && ln -s libpthread.so.20.0.27 libpthread.so.20; }; })
(cd /home/mohamed/research/thread_lib/gnu-pth/install/lib && { ln -s -f libpthread.so.20.0.27 libpthread.so || { rm -f libpthread.so && ln -s libpthread.so.20.0.27 libpthread.so; }; })
./shtool install -c .libs/libpthread.lai /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpthread.la
./shtool install -c .libs/libpthread.a /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpthread.a
chmod 644 /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpthread.a
ranlib /home/mohamed/research/thread_lib/gnu-pth/install/lib/libpthread.a
PATH="$PATH:/sbin" ldconfig -n /home/mohamed/research/thread_lib/gnu-pth/install/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/mohamed/research/thread_lib/gnu-pth/install/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
make[1]: Leaving directory '/home/mohamed/research/thread_lib/gnu-pth'
make[1]: Entering directory '/home/mohamed/research/thread_lib/gnu-pth'

Now use the package (you can remove it later via `make uninstall').
Additionally you should consider subscribing to the GNU Pth support
mailing list pth-users@gnu.org by running the following command:
`echo "subscribe pth-users" | mail pth-users-request@gnu.org'

make[1]: Leaving directory '/home/mohamed/research/thread_lib/gnu-pth
